name: 'smorgasbord-action-build-test'

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Install
        run: npm install
      -
        name: Verify Build
        run: |
          npm run clean
          npm run lint
          npm run build

  test:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Verify Run
        uses: ./
        with:
          fqdn: 'https://vapurrmaid.ca'
